# https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# https://classic.yarnpkg.com/en/docs/cli/cache#toc-yarn-cache-dir

name: "Determine yarn cache directory"

description: "Determines the yarn cache directory and exports it as YARN_CACHE_DIR environment variable"

inputs:
  working-directory:
    description: "Which directory to use as working directory"
    required: false
    default: "."

runs:
  using: "composite"

  steps:
    - name: "Determine yarn cache directory"
      shell: "bash"
      run: "echo \"YARN_CACHE_DIR=$(yarn cache dir --cwd=\"${{ env.YARN_WORKING_DIRECTORY }}\")\" >> $GITHUB_ENV"
      env:
        YARN_WORKING_DIRECTORY: "${{ inputs.working-directory }}"
